// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT-qK8jxfl9g4ssHi7oTAYn1UMbVnpkxI',
    appId: '1:442936560272:web:dfd276e59dc5797ad6e615',
    messagingSenderId: '442936560272',
    projectId: 'taskmanagerdesktop',
    authDomain: 'taskmanagerdesktop.firebaseapp.com',
    storageBucket: 'taskmanagerdesktop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIN331YUhU09xoUAnZDJn5fEvw4rndRYg',
    appId: '1:442936560272:android:dfcf4e059c4f61b8d6e615',
    messagingSenderId: '442936560272',
    projectId: 'taskmanagerdesktop',
    storageBucket: 'taskmanagerdesktop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjShdgtRlLuKgGeHyddIeOOhY4aFIP2YU',
    appId: '1:442936560272:ios:b9896898762b3d57d6e615',
    messagingSenderId: '442936560272',
    projectId: 'taskmanagerdesktop',
    storageBucket: 'taskmanagerdesktop.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjShdgtRlLuKgGeHyddIeOOhY4aFIP2YU',
    appId: '1:442936560272:ios:b9896898762b3d57d6e615',
    messagingSenderId: '442936560272',
    projectId: 'taskmanagerdesktop',
    storageBucket: 'taskmanagerdesktop.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT-qK8jxfl9g4ssHi7oTAYn1UMbVnpkxI',
    appId: '1:442936560272:web:99e3b840d9709f2ed6e615',
    messagingSenderId: '442936560272',
    projectId: 'taskmanagerdesktop',
    authDomain: 'taskmanagerdesktop.firebaseapp.com',
    storageBucket: 'taskmanagerdesktop.firebasestorage.app',
  );
}
